2025-07-18 22:18:01 | ROUTERS.INVOICE      | [91mERROR   [0m | Unexpected error processing Xendit callback: Could not determine join condition between parent/child tables on relationship HargaLayanan.pelanggan - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-07-18 22:33:33 | ROUTERS.INVOICE      | [91mERROR   [0m | Unexpected error processing Xendit callback: Could not determine join condition between parent/child tables on relationship HargaLayanan.paket_layanan - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-07-18 22:49:15 | JOBS                 | [91mERROR   [0m | [FAIL] Scheduler 'job_generate_invoices' failed. This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1048, "Column 'status_invoice' cannot be null")
[SQL: INSERT INTO invoices (invoice_number, pelanggan_id, id_pelanggan, brand, total_harga, no_telp, email, tgl_invoice, tgl_jatuh_tempo, status_invoice, payment_link, expiry_date, xendit_id, xendit_external_id, paid_amount, paid_at, is_processing, deleted_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('INV-20250718-78EACF', 1, 'ART-001', 'Jakinet', 388500.0, '08986937819', 'budi@test.com', datetime.date(2025, 7, 18), datetime.date(2025, 7, 23), None, None, None, None, None, None, None, 0, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
